"""
Probe script for bug: src--incremental_reasoner-py--_topdown_ordered_fqns

Tests whether _topdown_ordered_fqns returns functions in caller-before-callee
order (spec) or callee-before-caller order (claimed bug).

The function reads per-phase topdown layer JSON files generated by
generate_topdown_layers. Each layer file orders functions so that layer 0
contains top-level callers (no callers of their own within the phase), layer 1
contains their direct callees, etc.  Sorting layers ascending already yields
caller-first ordering.  This probe verifies that behaviour with a controlled
fixture and checks a real caller-callee pair from the project's own data.
"""

import json
import os
import shutil
import sys
import tempfile
from unittest.mock import patch

# ---------------------------------------------------------------------------
# Test 1 – controlled fixture: caller in layer 0, callee in layer 1
# ---------------------------------------------------------------------------
tmpdir = tempfile.mkdtemp(prefix="fma_probe_topdown_")
try:
    phases = {"phases": [{"phase": 1, "name": "ProbePhase"}]}
    with open(os.path.join(tmpdir, "phases.json"), "w") as f:
        json.dump(phases, f)

    os.makedirs(os.path.join(tmpdir, "spec_prompts"), exist_ok=True)
    layer_fixture = {
        "phase": 1,
        "phase_name": "ProbePhase",
        "layers": [
            {
                "layer": 0,
                "functions": [
                    {"name": "mod::caller_a"},
                    {"name": "mod::caller_b"},
                ],
            },
            {
                "layer": 1,
                "functions": [
                    {"name": "mod::callee_x"},
                    {"name": "mod::callee_y"},
                ],
            },
            {
                "layer": 2,
                "functions": [
                    {"name": "mod::leaf_z"},
                ],
            },
        ],
    }
    with open(
        os.path.join(tmpdir, "spec_prompts", "phase_01_topdown_layers.json"), "w"
    ) as f:
        json.dump(layer_fixture, f)

    with patch(
        "src.incremental_reasoner.generate_topdown_layers", return_value=None
    ), patch("src.incremental_reasoner._load_phases", return_value=phases):
        from src.incremental_reasoner import _topdown_ordered_fqns

        result = _topdown_ordered_fqns(tmpdir)

    # Every caller (layer 0) must appear before every callee (layers 1, 2)
    callers = {"mod::caller_a", "mod::caller_b"}
    callees = {"mod::callee_x", "mod::callee_y", "mod::leaf_z"}
    all_expected = callers | callees

    missing = all_expected - set(result)
    unexpected = set(result) - all_expected

    if missing:
        print(f"ERROR — fixture test: missing expected FQNs: {missing}")
        sys.exit(1)
    if unexpected:
        print(f"ERROR — fixture test: unexpected FQNs in result: {unexpected}")
        sys.exit(1)

    last_caller_idx = max(result.index(f) for f in callers)
    first_callee_idx = min(result.index(f) for f in callees)

    if last_caller_idx < first_callee_idx:
        print(
            f"Fixture test: callers (max idx {last_caller_idx}) precede "
            f"callees (min idx {first_callee_idx}) — ordering is caller-first"
        )
    else:
        print(
            f"Fixture test: at least one callee (min idx {first_callee_idx}) "
            f"precedes a caller (max idx {last_caller_idx}) "
            f"— ordering is NOT caller-first"
        )
finally:
    shutil.rmtree(tmpdir, ignore_errors=True)

# ---------------------------------------------------------------------------
# Test 2 – real data: dashboard-py::main (layer 0) vs
#           dashboard-py::State::__init__ (layer 1)
#
# Use the project's existing fm_agent artifacts via a copy so the probe does
# not mutate the active data.
# ---------------------------------------------------------------------------
tmpdir2 = tempfile.mkdtemp(prefix="fma_probe_real_")
try:
    # __file__ is at fm_agent/bug_validation/probe_...py
    # FM-Agent repo root is three levels up from the probe script
    repo_root = os.path.dirname(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    )
    real_work_dir = os.path.join(repo_root, "fm_agent")
    phases_json_path = os.path.join(real_work_dir, "phases.json")
    spec_prompts_src = os.path.join(real_work_dir, "spec_prompts")
    spec_prompts_dst = os.path.join(tmpdir2, "spec_prompts")

    if os.path.isfile(phases_json_path):
        shutil.copy2(phases_json_path, os.path.join(tmpdir2, "phases.json"))
    if os.path.isdir(spec_prompts_src):
        shutil.copytree(spec_prompts_src, spec_prompts_dst, dirs_exist_ok=True)

    with patch(
        "src.incremental_reasoner.generate_topdown_layers", return_value=None
    ):
        from src.incremental_reasoner import _topdown_ordered_fqns

        result = _topdown_ordered_fqns(tmpdir2)

    # Known relationship: dashboard-py::main calls dashboard-py::State::__init__
    main_key = "dashboard-py::main"
    init_key = "dashboard-py::State::__init__"

    if main_key in result and init_key in result:
        main_idx = result.index(main_key)
        init_idx = result.index(init_key)
        if main_idx < init_idx:
            formatted = f"caller@{main_idx} precedes callee@{init_idx}"
            print(f"Real-data test: {formatted}")
        else:
            formatted = f"callee@{init_idx} precedes caller@{main_idx}"
            print(f"Real-data test: {formatted}")
    else:
        missing_real = []
        if main_key not in result:
            missing_real.append(main_key)
        if init_key not in result:
            missing_real.append(init_key)
        print(
            f"Real-data test: skipped — FQNs missing from result: {missing_real}"
        )
finally:
    shutil.rmtree(tmpdir2, ignore_errors=True)

# ---------------------------------------------------------------------------
# Final verdict
# ---------------------------------------------------------------------------
# If we got here without ERROR, both tests saw caller-first ordering.
print(
    "NOT CONFIRMED — _topdown_ordered_fqns returns callers before callees "
    "(layer 0 before layer 1+), matching the specification. "
    "The MISMATCH claim of callee-first ordering is a false positive."
)
