def _codegraph_functions_by_file(proj_dir, lang_keys):
    """Return CodeGraph's ``{relative path: {identifier: source}}`` mapping.

    CodeGraph uses class-qualified identifiers for C++ methods, so comparing two
    mappings generated by it avoids the ambiguity of the regex extractor's bare
    method names. ``None`` means that no usable CodeGraph index is available.
    """
    extractor = CodeGraphExtractor.from_proj_dir(proj_dir)
    if extractor is None:
        return None

    result = {}
    for lang_key in sorted(lang_keys):
        for abs_path, functions in extractor.get_functions_by_file(
            lang_key, proj_dir
        ).items():
            result[_normalized_relative_path(proj_dir, abs_path)] = dict(functions)
    return result
